### ISSUE TITLE
How to run ALTS?

### ISSUE THREAD

**Issue by Arman1zz** [DanielVandH/ALTS#3]
Dear publisher:
    Recently I am trying to reproduce the ALTS model in your paper, but I don't know how to do it.
    Could you please explain it in detail? Thanks for your share!

**Comment by DanielVandH** [comment]
Hi @Arman1zz, 

I listed the steps for how to reproduce the paper in the README at https://github.com/DanielVandH/ALTS?tab=readme-ov-file#steps-to-reproduce-the-paper. Can you please explain what might not be clear there? Basically you need to just download the files from the repository (see the green code button in the top-right above the files, click it and then download zip), and then run the files as mentioned in the README.

**Comment by DanielVandH** [comment]
Hi @Arman1zz,

> Where is the main entry of your code? Is it Paper_Code_Data.R?

The code is split into parts as described in the README. First, note that

- The algorithms themselves are defined in ALTS_Functions.R.
- The functions used for performing the case study are given in Case_Study_Functions.R.
- Some other functions for running the simulations are in Simulation_Functions.R.

For reproducing the actual results, you do it in two steps:

- Firstly, Paper_Code_Data.R is used to obtain the results for the paper, including the simulation study. So, yes, this is the main entry point.
- Code for reproducing the figures is in Paper_Code_Figure.R. Use this if you want to see how all the data is used.

To run all this, open R with all these files in your working directory and it should just work. Note that (as far as I remember from when I last ran this code) Paper_Code_Data.R can take a bit of time to complete.

> If I want to run your code with my own dataset(the same base model GEFC2012 proposed by Hong), how do I fit it with my data?

See the ALTS_Functions.R script. Specifically, the `ALTS` function does the model fitting. In that file it is hopefully sufficiently documented for you to understand how to use it. For example, in the case study, the function `random_attack_ALTS` on L122 of Case_Study_Functions.R works fits the data using our ALTS method in lines 125-131, using the dataset `new_data` (which is just the data you mention except with some attacked data) (this data, and the model formula, are defined in Paper_Code_Data.R, see L65-L135).

Hope that helps.

**Comment by DanielVandH** [comment]
> Is it Paper_Code_Data.R? I failed to run the Paper_Code_Data.R. 

I saw that you added this while I was making my response but hopefully my point

> To run all this, open R with all these files in your working directory and it should just work. Note that (as far as I remember from when I last ran this code) Paper_Code_Data.R can take a bit of time to complete.

will help address whatever error you saw. Otherwise, send the error so I can see what's going wrong

**Comment by Arman1zz** [comment]
Hi@DanielVandH ,
Thank you very much for your patient and complete reply. 
I'll take your advice well.

Thank you. Have a good life!

**Comment by DanielVandH** [comment]
No problem, happy to help. I'll close this issue for now but feel free to ask if there are still problems.

**Comment by Arman1zz** [comment]
Hi@DanielVandH ，

Errors occurs when I run the Paper_Code_Data.R. 

More precisely, errors occurred in "Economic loss study"/ "Economic loss study: Smaller mu, larger sigma"/ "Economic loss study: Smaller mu, larger sigma"......

The errors from these code blocks all point to the function — "random_attack_all_simulations_grid_vals". And the same issue is also present in function ramp_attack_all_simulations_grid_vals.

My execution process is as follows:
1. Setwd workspace and Load the functions and libraries. (line 4-24) — success
2. Executive "Read in the case study data". (line 65-135) — success
3. Executive "Economic loss study". (line 140-149) —error

**Comment by Arman1zz** [comment]
The error message is as follows: stop("'arg' must be of length 1")
![image](https://github.com/user-attachments/assets/9cf02811-0208-49eb-9f15-61377cea1a90)
![image](https://github.com/user-attachments/assets/a4b33d19-c0b8-4037-97f4-ea76670b27af)

**Comment by DanielVandH** [comment]
I'll look into this soon
