### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by Arman1zz** [DanielVandH/ALTS#4]
Hi@DanielVandH ，

Errors occurs when I run the Paper_Code_Data.R.

More precisely, errors occurred in "Economic loss study"/ "Economic loss study: Smaller mu, larger sigma"/ "Economic loss study: Smaller mu, larger sigma"......

The errors from these code blocks all point to the function — "random_attack_all_simulations_grid_vals". And the same issue is also present in function ramp_attack_all_simulations_grid_vals.

My execution process is as follows:

Setwd workspace and Load the functions and libraries. (line 4-24) — success
Executive "Read in the case study data". (line 65-135) — success
Executive "Economic loss study". (line 140-149) —error

Error Message: stop("'arg' must be of length 1")
![image](https://github.com/user-attachments/assets/a085b1ed-d417-42ff-977a-3858c932d3bf)
![image](https://github.com/user-attachments/assets/70a47a0c-8ccb-4fe5-a1e1-4a9ea920bea2)

**Comment by DanielVandH** [comment]
So this is a bug in the `rq` library or `conquer`, I'm not sure. The `ci` argument in `conquer` is being given `FALSE` by `rq` which errors. I can fix the `match.arg(kernel)` bug by passing `kernel = "Gaussian"` but the next line also errors.

Let me try and find the minimum working version of these libraries. I haven't used R since this project so I'll have to familiarize myself again.

**Comment by DanielVandH** [comment]
At the top of Paper_Code_Data.R, can you try placing 

```R
library(conquer)

patch_rq_fit_conquer <- function (x, y, tau = 0.5, kernel = c("Gaussian", "uniform", 
                                                              "parabolic", "triangular"), h = 0, tol = 1e-04, iteMax = 5000, 
                                  ci = FALSE, alpha = 0.05, B = 200) 
{
  if (!requireNamespace("conquer", quietly = TRUE)) 
    stop("method conquer requires package conquer")
  fit = conquer::conquer(x[, -1], y, tau = tau, kernel = kernel, 
                         h = h, tol = tol, iteMax = iteMax, ci = ci, alpha = alpha, 
                         B = 1000)  # <-- here, passing ci as an argument (original version used ci = FALSE)
  coefficients = fit$coeff
  names(coefficients) = dimnames(x)[[2]]
  residuals = fit$residual
  list(coefficients = coefficients, tau = tau, residuals = residuals)
}

# Overriding the function in the package's namespace
assignInNamespace("rq.fit.conquer", patch_rq_fit_conquer, ns = "quantreg")
```

(meaning right above the simulation study header in that file)?

If that works I'll update the repo and also upload the package versions so it's reproducible (which I should have done initially but two years ago I didn't know any better I guess).

**Comment by DanielVandH** [comment]
Actually that still won't work. I've updated the repo with a fix. Can you redownload it and try now? Use `renv::restore()` to make sure our package versions match

**Comment by Arman1zz** [comment]
Hello@DanielVandH 

Thank you very much for your patience and detailed response!

The code you re-uploaded is now running successfully. I also observed that the experimental results are very close to those in the paper. I will carefully study your code to see if tweaking the parameters can yield even better results.

Once again, thank you for your effort! 
Wishing you all the best in your research and a wonderful life ahead!

**Comment by DanielVandH** [comment]
Great!
